### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Vedansh",
  "email": "vedanh@gmail.com",
  "address": "blr",
  "dateOfBirth": "1998-03-09",
  "registeredDate": "2009-11-28"
}

###