spring.application.name=patient-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://patient-service-db:5432/${POSTGRES_DB:db}
spring.datasource.username=${POSTGRES_USER:admin_user}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000
logging.level.root=info

# Billing Service Configuration
billing.service.address=billing-service
billing.service.grpc.port=9001